language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-tze' ]; then cd .. && eval "mv $currentfolder generator-tze" && cd generator-tze; fi
deploy:
  provider: npm
  email: "tclei2009@gmail.com"
  api_key: "aRSU5ovaqnFPeU9b9sVr"
  on:
    tags: true